### PR TITLE
Add hidden directories toggle

### PR DESCRIPTION
**Pull request by ianacl**

### CODE REVIEW

**Comment by SebastianZimmeck** [comment]
Thanks a bunch @atierian. Could you say a few words on this PR? What issue did you encounter?

(cc'ing @davebaraka and @rgoldstein01)

**Comment by ianacl** [comment]
Hi Sebastian,

Thanks for your reply.
I love the app, thanks for creating it! 

I tend to work with hidden directories and wanted to be able to easily access project folders that are located in hidden directories from within privacyflash-pro.
I figured other developers may also want this functionality.

No hard feelings if you don’t want to use it or if you have a better way of implementing it, I just thought it might be a nice additional feature.

p.s. I implemented this for myself with a checkbox instead of a button, but made the pull request with the button to closer mirror your UI.

Let me know if you have any questions. 

Best
Ian

On Jan 12, 2020, at 3:30 PM, Sebastian Zimmeck <notifications@github.com <mailto:notifications@github.com> > wrote:

Thanks a bunch @atierian. Could you say a few words on this PR? What issue did you encounter?

(cc'ing @davebaraka and @rgoldstein01)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

<http://schema.org>

**Comment by SebastianZimmeck** [comment]
> I tend to work with hidden directories and wanted to be able to easily access project folders that are located in hidden directories from within privacyflash-pro.
I figured other developers may also want this functionality.

Absolutely! Thank you, Ian. It seems that this is mostly what @davebaraka was working on.

**Comment by davebaraka** [comment]
Great! Thank you @atierian

**Pull request merged**
